import type { Product, Category, Collection } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Outerwear', slug: 'outerwear', createdAt: new Date().toISOString() },
  { id: 'cat-2', name: 'Tops', slug: 'tops', createdAt: new Date().toISOString() },
  { id: 'cat-3', name: 'Bottoms', slug: 'bottoms', createdAt: new Date().toISOString() },
  { id: 'cat-4', name: 'Dresses', slug: 'dresses', createdAt: new Date().toISOString() },
  { id: 'cat-5', name: 'Accessories', slug: 'accessories', createdAt: new Date().toISOString() },
  { id: 'cat-6', name: 'Perfumes', slug: 'perfumes', createdAt: new Date().toISOString() }
];

export const MOCK_COLLECTIONS: Collection[] = [
  { id: 'col-1', name: 'Staples Collection', slug: 'staples-collection', createdAt: new Date().toISOString() },
  { id: 'col-2', name: 'Drape & Structure', slug: 'drape-structure', createdAt: new Date().toISOString() }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    categoryId: 'cat-2',
    collectionId: 'col-1',
    name: 'FR Core Oversized Cotton Tee',
    slug: 'fr-core-oversized-cotton-tee',
    description: 'Cut from premium 280GSM organic cotton jersey, this oversized tee features dropped shoulders, a tight rib mock collar, and a structural drape that holds its shape. Tailored for a modern, relaxed silhouette.',
    basePrice: 2800.00,
    isPublished: true,
    images: ['/assets/tee_white.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.8,
    reviewsCount: 34,
    tags: ['new-arrivals', 'best-sellers'],
    parentCategory: 'men',
    subCategory: 'oversized-t-shirts',
    variants: [
      { id: 'v-1-s', productId: 'prod-1', size: 'S', color: 'Ivory White', sku: 'FR-COT-OW-S', stockQty: 15, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-1-m', productId: 'prod-1', size: 'M', color: 'Ivory White', sku: 'FR-COT-OW-M', stockQty: 22, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-1-l', productId: 'prod-1', size: 'L', color: 'Ivory White', sku: 'FR-COT-OW-L', stockQty: 18, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-2',
    categoryId: 'cat-2',
    collectionId: 'col-1',
    name: 'Oatmeal Bouclé Boxy Hoodie',
    slug: 'oatmeal-boucle-boxy-hoodie',
    description: 'Crafted from heavyweight bouclé cotton-blend fleece, this hoodie offers exceptional thermal warmth and texture. Featuring a boxy fit, double-lined hood with no drawstrings for a clean profile, and a wide kangaroo pocket.',
    basePrice: 6500.00,
    isPublished: true,
    images: ['/assets/knit_hoodie.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.9,
    reviewsCount: 22,
    tags: ['trending', 'new-arrivals'],
    parentCategory: 'men',
    subCategory: 'hoodies',
    variants: [
      { id: 'v-2-s', productId: 'prod-2', size: 'S', color: 'Oatmeal Melange', sku: 'FR-OBH-S', stockQty: 10, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-2-m', productId: 'prod-2', size: 'M', color: 'Oatmeal Melange', sku: 'FR-OBH-M', stockQty: 12, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-2-l', productId: 'prod-2', size: 'L', color: 'Oatmeal Melange', sku: 'FR-OBH-L', stockQty: 8, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-3',
    categoryId: 'cat-1',
    collectionId: 'col-2',
    name: 'Structured Kimono Jacket',
    slug: 'structured-kimono-jacket',
    description: 'Tailored from crisp, mid-weight linen-cotton twill. Featuring structural front patch pockets, wide kimono-cut sleeves, a minimalist band collar, and a sleek waist sash closure.',
    basePrice: 8500.00,
    isPublished: true,
    images: ['/assets/kimono_shirt.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    collection: MOCK_COLLECTIONS[1],
    rating: 4.7,
    reviewsCount: 16,
    tags: ['featured-collection'],
    parentCategory: 'men',
    subCategory: 'jackets',
    variants: [
      { id: 'v-3-s', productId: 'prod-3', size: 'S', color: 'Ivory Cream', sku: 'FR-SKJ-IC-S', stockQty: 14, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-3-m', productId: 'prod-3', size: 'M', color: 'Ivory Cream', sku: 'FR-SKJ-IC-M', stockQty: 16, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-3-l', productId: 'prod-3', size: 'L', color: 'Ivory Cream', sku: 'FR-SKJ-IC-L', stockQty: 10, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-4',
    categoryId: 'cat-3',
    collectionId: 'col-1',
    name: 'Relaxed Silk-Blend Utility Trouser',
    slug: 'relaxed-silk-blend-utility-trouser',
    description: 'A contemporary take on utility wear, these trousers are woven from a premium silk-linen blend. Featuring an elasticated waistband, side cargo pockets, and adjustable tab hems.',
    basePrice: 9200.00,
    isPublished: true,
    images: ['/assets/silk_trouser.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.6,
    reviewsCount: 19,
    tags: ['trending', 'best-sellers'],
    parentCategory: 'men',
    subCategory: 'cargo-pants',
    variants: [
      { id: 'v-4-s', productId: 'prod-4', size: 'S', color: 'Off-Black', sku: 'FR-SUT-OB-S', stockQty: 12, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-4-m', productId: 'prod-4', size: 'M', color: 'Off-Black', sku: 'FR-SUT-OB-M', stockQty: 15, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-4-l', productId: 'prod-4', size: 'L', color: 'Off-Black', sku: 'FR-SUT-OB-L', stockQty: 11, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-5',
    categoryId: 'cat-4',
    collectionId: 'col-2',
    name: 'Minimalist Silk Slip Dress',
    slug: 'minimalist-silk-slip-dress',
    description: 'A bias-cut dress crafted from ultra-soft sandwashed silk. Designed with thin spaghetti straps, a graceful cowl neckline, and a fluid silhouette that flows effortlessly.',
    basePrice: 12500.00,
    isPublished: true,
    images: ['/assets/slip_dress.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
    collection: MOCK_COLLECTIONS[1],
    rating: 4.9,
    reviewsCount: 28,
    tags: ['best-sellers', 'featured-collection'],
    parentCategory: 'women',
    subCategory: 'dresses',
    variants: [
      { id: 'v-5-xs', productId: 'prod-5', size: 'XS', color: 'Midnight Noir', sku: 'FR-MSD-MN-XS', stockQty: 8, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-5-s', productId: 'prod-5', size: 'S', color: 'Midnight Noir', sku: 'FR-MSD-MN-S', stockQty: 14, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-5-m', productId: 'prod-5', size: 'M', color: 'Midnight Noir', sku: 'FR-MSD-MN-M', stockQty: 10, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-6',
    categoryId: 'cat-1',
    collectionId: 'col-2',
    name: 'Linen Belted Trench Coat',
    slug: 'linen-belted-trench-coat',
    description: 'A fluid, double-breasted trench coat tailored from mid-weight Belgian linen. Features an asymmetric storm flap, classic shoulder epaulets, and a matching waist sash tie belt.',
    basePrice: 14500.00,
    isPublished: true,
    images: ['/assets/trench_coat.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    collection: MOCK_COLLECTIONS[1],
    rating: 4.8,
    reviewsCount: 42,
    tags: ['featured-collection', 'new-arrivals'],
    parentCategory: 'women',
    subCategory: 'dresses',
    variants: [
      { id: 'v-6-s', productId: 'prod-6', size: 'S', color: 'Natural Flax', sku: 'FR-LBTC-NF-S', stockQty: 8, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-6-m', productId: 'prod-6', size: 'M', color: 'Natural Flax', sku: 'FR-LBTC-NF-M', stockQty: 12, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-7',
    categoryId: 'cat-5',
    collectionId: 'col-1',
    name: 'Structured Cotton Twill Cap',
    slug: 'structured-cotton-twill-cap',
    description: 'A minimal six-panel cap made from durable cotton twill. Features an adjustable back strap with a custom brass buckle and a subtly curved brim.',
    basePrice: 2200.00,
    isPublished: true,
    images: ['/assets/cap_1784646670746.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.6,
    reviewsCount: 15,
    tags: ['new-arrivals'],
    parentCategory: 'accessories',
    subCategory: 'caps',
    variants: [
      { id: 'v-7-os', productId: 'prod-7', size: 'One Size', color: 'Sand Beige', sku: 'FR-SCT-SB', stockQty: 50, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-8',
    categoryId: 'cat-6',
    collectionId: 'col-1',
    name: 'Nuit Noire Intense (Unisex)',
    slug: 'nuit-noire-intense',
    description: 'An elegant blend of smoky vetiver, leather, black pepper, and cedarwood notes. Woven together to create a dark, woody scent trail that lasts all day.',
    basePrice: 6800.00,
    isPublished: true,
    images: ['/assets/sneakers_1784646656235.png'], // Reusing sneakers image as a visual aesthetic container
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[5],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.9,
    reviewsCount: 37,
    tags: ['trending', 'best-sellers'],
    parentCategory: 'perfumes',
    subCategory: 'unisex',
    variants: [
      { id: 'v-8-50ml', productId: 'prod-8', size: '50ml', color: 'Smoky Wood', sku: 'FR-NNI-50', stockQty: 25, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-8-100ml', productId: 'prod-8', size: '100ml', color: 'Smoky Wood', sku: 'FR-NNI-100', stockQty: 18, additionalPrice: 2400, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-9',
    categoryId: 'cat-2',
    collectionId: 'col-1',
    name: 'Oversized Boxy Tee in Washed Black',
    slug: 'oversized-boxy-tee-washed-black',
    description: 'Cut from heavyweight 320GSM pre-shrunk cotton, this tee is finished with an antique wash for a relaxed, premium look. Features structural dropped shoulders and a mock rib neck.',
    basePrice: 3200.00,
    isPublished: true,
    images: ['/assets/hoodie_black_1784646596372.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.8,
    reviewsCount: 29,
    tags: ['new-arrivals', 'trending'],
    parentCategory: 'men',
    subCategory: 'oversized-t-shirts',
    variants: [
      { id: 'v-9-s', productId: 'prod-9', size: 'S', color: 'Washed Black', sku: 'FR-OBT-WB-S', stockQty: 15, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-9-m', productId: 'prod-9', size: 'M', color: 'Washed Black', sku: 'FR-OBT-WB-M', stockQty: 20, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-9-l', productId: 'prod-9', size: 'L', color: 'Washed Black', sku: 'FR-OBT-WB-L', stockQty: 12, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-10',
    categoryId: 'cat-3',
    collectionId: 'col-1',
    name: 'Heavy Cotton Cargo Pants',
    slug: 'heavy-cotton-cargo-pants',
    description: 'Tailored from rugged cotton drill, these cargo pants feature double knee reinforcement, side cargo pockets with hidden press buttons, and adjustable cotton ties at the hems.',
    basePrice: 5800.00,
    isPublished: true,
    images: ['/assets/cargo_pants_1784646641064.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.7,
    reviewsCount: 24,
    tags: ['trending', 'best-sellers'],
    parentCategory: 'men',
    subCategory: 'cargo-pants',
    variants: [
      { id: 'v-10-30', productId: 'prod-10', size: '30', color: 'Olive Drab', sku: 'FR-HCCP-OD-30', stockQty: 10, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-10-32', productId: 'prod-10', size: '32', color: 'Olive Drab', sku: 'FR-HCCP-OD-32', stockQty: 15, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-10-34', productId: 'prod-10', size: '34', color: 'Olive Drab', sku: 'FR-HCCP-OD-34', stockQty: 8, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-11',
    categoryId: 'cat-2',
    collectionId: 'col-1',
    name: 'Cropped Organic Linen Top',
    slug: 'cropped-organic-linen-top',
    description: 'Designed with a square neckline, wide structural straps, and a clean zippered back closure. Tailored from premium flax linen.',
    basePrice: 3800.00,
    isPublished: true,
    images: ['/assets/kimono_shirt.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.5,
    reviewsCount: 14,
    tags: ['new-arrivals', 'sale'],
    parentCategory: 'women',
    subCategory: 'tops',
    variants: [
      { id: 'v-11-xs', productId: 'prod-11', size: 'XS', color: 'Ivory Flax', sku: 'FR-COLT-IF-XS', stockQty: 12, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-11-s', productId: 'prod-11', size: 'S', color: 'Ivory Flax', sku: 'FR-COLT-IF-S', stockQty: 18, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-11-m', productId: 'prod-11', size: 'M', color: 'Ivory Flax', sku: 'FR-COLT-IF-M', stockQty: 10, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-12',
    categoryId: 'cat-3',
    collectionId: 'col-1',
    name: 'Wide-Leg Selvedge Denim',
    slug: 'wide-leg-selvedge-denim',
    description: 'Crafted from 14oz Japanese raw indigo selvedge denim. Over time, these jeans develop unique character custom to the wearer.',
    basePrice: 7800.00,
    isPublished: true,
    images: ['/assets/silk_trouser.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.8,
    reviewsCount: 19,
    tags: ['trending', 'best-sellers'],
    parentCategory: 'men',
    subCategory: 'jeans',
    variants: [
      { id: 'v-12-30', productId: 'prod-12', size: '30', color: 'Raw Indigo', sku: 'FR-WLSD-RI-30', stockQty: 8, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-12-32', productId: 'prod-12', size: '32', color: 'Raw Indigo', sku: 'FR-WLSD-RI-32', stockQty: 12, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-12-34', productId: 'prod-12', size: '34', color: 'Raw Indigo', sku: 'FR-WLSD-RI-34', stockQty: 6, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-13',
    categoryId: 'cat-5',
    collectionId: 'col-1',
    name: 'Minimalist Full-Grain Leather Belt',
    slug: 'minimalist-leather-belt',
    description: 'Handcrafted from 4mm thick full-grain vegetable-tanned bridle leather. Worn with a minimal solid brass buckle.',
    basePrice: 3500.00,
    isPublished: true,
    images: ['/assets/jacket_neon_1784646612273.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.7,
    reviewsCount: 31,
    tags: ['best-sellers'],
    parentCategory: 'accessories',
    subCategory: 'belts',
    variants: [
      { id: 'v-13-m', productId: 'prod-13', size: '32-34', color: 'Rich Tan', sku: 'FR-MGLB-RT', stockQty: 25, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-13-l', productId: 'prod-13', size: '36-38', color: 'Rich Tan', sku: 'FR-MGLB-RT-L', stockQty: 20, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-14',
    categoryId: 'cat-6',
    collectionId: 'col-1',
    name: 'Santal Ethereal EDP',
    slug: 'santal-ethereal-edp',
    description: 'An airy, sophisticated fragrance structured with Australian sandalwood, cardamom, violet accord, and clean papyrus notes.',
    basePrice: 7500.00,
    isPublished: true,
    images: ['/assets/cap_1784646670746.png'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[5],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.9,
    reviewsCount: 46,
    tags: ['best-sellers', 'new-arrivals'],
    parentCategory: 'perfumes',
    subCategory: 'men',
    variants: [
      { id: 'v-14-50', productId: 'prod-14', size: '50ml', color: 'Sandalwood Amber', sku: 'FR-SE-50', stockQty: 18, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-15',
    categoryId: 'cat-6',
    collectionId: 'col-1',
    name: 'Soleil D\'Or Eau De Parfum',
    slug: 'soleil-dor-edp',
    description: 'A luminous, bright fragrance capturing Sicilian bergamot, neroli blossoms, soft amber, and clean coastal sea salt.',
    basePrice: 5800.00,
    isPublished: true,
    images: ['/assets/tee_white.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[5],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.6,
    reviewsCount: 18,
    tags: ['sale'],
    parentCategory: 'perfumes',
    subCategory: 'women',
    variants: [
      { id: 'v-15-50', productId: 'prod-15', size: '50ml', color: 'Citrus Neroli', sku: 'FR-SDO-50', stockQty: 15, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  },
  {
    id: 'prod-16',
    categoryId: 'cat-2',
    collectionId: 'col-1',
    name: 'Minimalist Cashmere Knit Sweater',
    slug: 'minimalist-cashmere-knit-sweater',
    description: 'Woven from premium long-staple Mongolian cashmere, this sweater is soft, lightweight, and insulating. Features a structural mock neck and relaxed drop shoulders.',
    basePrice: 11000.00,
    isPublished: true,
    images: ['/assets/knit_hoodie.jpg'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    collection: MOCK_COLLECTIONS[0],
    rating: 4.9,
    reviewsCount: 23,
    tags: ['featured-collection', 'new-arrivals'],
    parentCategory: 'women',
    subCategory: 'tops',
    variants: [
      { id: 'v-16-s', productId: 'prod-16', size: 'S', color: 'Ivory Melange', sku: 'FR-MCKS-IM-S', stockQty: 10, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
      { id: 'v-16-m', productId: 'prod-16', size: 'M', color: 'Ivory Melange', sku: 'FR-MCKS-IM-M', stockQty: 12, additionalPrice: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
    ]
  }
];
